apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: zabbix-azul
  creationTimestamp: null
  labels:
    zabbix-app: zabbix-web
  name: zabbix-web-nginx-mysql
spec:
  selector:
    matchLabels:
      zabbix-app: zabbix-web
  serviceName: "zabbix-web-nginx-mysql"
  replicas: 3
  #strategy:
  #  type: Recreate
  template:
    metadata:
      labels:
        zabbix-app: zabbix-web
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: dc
                operator: In
                values:
                - glete
      containers:
        - name: zabbix-web
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE
                  name: zabbix-app
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_USER
                  name: zabbix-app
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: zabbix-app
            - name: ZBX_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  key: ZBX_SERVER_HOST
                  name: zabbix-app
            - name: ZBX_SERVER_NAME
              valueFrom:
                configMapKeyRef:
                  key: ZBX_SERVER_NAME
                  name: zabbix-app
            - name: DB_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  key: DB_SERVER_HOST
                  name: zabbix-app
            - name: PHP_TZ
              valueFrom:
                configMapKeyRef:
                  key: PHP_TZ
                  name: zabbix-app  
          image: zabbix/zabbix-web-nginx-mysql:ubuntu-4.0.11
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
  volumeClaimTemplates: []
  
---

apiVersion: v1
kind: Service
metadata:
  namespace: zabbix-azul
  annotations:
  creationTimestamp: null
  labels:
    zabbix-app: zabbix-web
  name: zabbix-web-nginx-mysql
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 80
    - name: "https"
      port: 443
      targetPort: 443
  selector:
    zabbix-app: zabbix-web
  type: LoadBalancer
